//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasks_table
    {
        public int id { get; set; }
        public string tasks { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
    
        public virtual status_table status_table { get; set; }
    }
}
